apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.app }}-dpl
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.app }}
    spec:
    # select only all the key:values inside specific key
      nodeSelector: 
      {{- toYaml .Values.nodeSelector | nindent 7 }}
      containers:
      - name: {{ .Values.appName.app }}-cont
        image: {{ .Values.container.image }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env: 
        {{- range .Values.container.envs }}
          - name: {{ .name }}
            value: {{ .value }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.container.port }}
