---
- name: Deploy Database 
  hosts: worker2 
  vars_files: 
    - ../vars/database_credential.yaml 
  tasks: 
    - name: Deploy Database 
      debug: 
        msg: "Database Password: {{ db_password }} \n Username is : {{ db_username }}"