apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stagging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: lyvanna544@gmail.com
    privateKeySecretRef:
      name: letsencrypt-stagging
    solvers:
    - http01:
        ingress:
          class: nginx