apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=

# echo -n "password123" | base64
#kubectl create secret generic postgres-secret --from-literal=POSTGRES_PASSWORD=password123
