apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpl
spec:
  replicas: 4
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: nginx-dpl
  template:
    metadata:
      labels:
        app: nginx-dpl
    spec:
      nodeSelector:
        kubernetes.io/hostname: node5
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
