apiVersion: v1
kind: Service
metadata:
  name: postgres-svc-headless
spec:
# if not specified , it's CluseterIP by default 
  #type: ClusterIP
  clusterIP: None
  selector:
    app: postgres-app
  ports:
  - port: 5432
    targetPort: 5432
